/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddInstitution: typeof import('./components/assetManager/addInstitution/addInstitution.vue')['default']
    AddInstitutionDialog: typeof import('./components/assetManager/addInstitution/addInstitutionDialog.vue')['default']
    AddNewAsset: typeof import('./components/assetManager/addNewAsset/addNewAsset.vue')['default']
    AddNewAssetDialog: typeof import('./components/assetManager/addNewAsset/addNewAssetDialog.vue')['default']
    FlowPathManagement: typeof import('./components/assetManager/flowPathManagement.vue')['default']
    ImportAssets: typeof import('./components/assetManager/importAssets/importAssets.vue')['default']
    ImportAssetsDialog: typeof import('./components/assetManager/importAssets/importAssetsDialog.vue')['default']
    MyAssets: typeof import('./components/assetManager/myAssets.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
